name = "mailg"
compatibility_date = "2026-03-01"
# Pages configuration
pages_build_output_dir = "dist"

[vars]
MAILGUN_DOMAIN = "dipankarshaw.qzz.io"

[[d1_databases]]
binding = "DB"
database_name = "analytics"
database_id = "9b8667e8-07ae-4d1c-96ae-205093312247"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "misc"

[observability]
enabled = true
